version: '3.7'

services:

  luigi:
    image: "nsidc/sipn-reanalysis-ingest:dev"
    build:
      context: "."
      args:
        NEW_MAMBA_USER_ID: "${MAMBA_USER_ID}"
        NEW_MAMBA_USER_GID: "${MAMBA_USER_GID}"

    volumes:
      - "./sipn_reanalysis_ingest:/app/sipn_reanalysis_ingest:ro"
      - "./tasks:/app/tasks:ro"
      - "./pyproject.toml:/app/pyproject.toml"
      - "./luigi.toml:/app/luigi.toml"
